template: Apache by HTTP
description: "This template is designed for the effortless deployment of Apache monitoring\
  \ by Zabbix via HTTP and doesn't require any external scripts.\r\n\r\nThe template\
  \ collects metrics by polling 'mod_status' with HTTP agent remotely.\r\n\r\nSetup:\r\
  \n\r\n1. See the setup instructions for mod_status:\r\nhttps://httpd.apache.org/docs/current/mod/mod_status.html\r\
  \n\r\nCheck the availability of the module with this command line:\r\nhttpd -M 2>/dev/null\
  \ | grep status_module\r\n\r\nThis is an example configuration of the Apache web\
  \ server:\r\n\r\n<Location \"/server-status\">\r\n  SetHandler server-status\r\n\
  \  Require host example.com\r\n</Location>\r\n\r\n2. Set the hostname or IP address\
  \ of the Apache status page host in the '{$APACHE.STATUS.HOST}' macro. You can also\
  \ change the status page port in the '{$APACHE.STATUS.PORT}' macro and status page\
  \ path in the '{$APACHE.STATUS.PATH}' macro if necessary.\r\n\r\nYou can discuss\
  \ this template or leave feedback on our forum https://www.zabbix.com/forum/zabbix-suggestions-and-feedback/384764-discussion-thread-for-official-zabbix-template-apache\r\
  \n\r\nGenerated by official Zabbix template tool \"Templator\""
groups:
- Templates
items:
- name: Total bytes
  key: apache.bytes
  interval: '0'
  type: dependent
  master_item_key: apache.get_status
  units: B
  description: The total bytes served.
  history: 31d
  tags:
  - tag: component
    value: network
- name: Bytes per second
  key: apache.bytes.rate
  interval: '0'
  type: dependent
  master_item_key: apache.get_status
  units: Bps
  description: "It is calculated as a rate of change for total bytes statistics.\r\
    \n`BytesPerSec` is not used, as it counts the average since the last Apache server\
    \ start."
  history: 31d
  tags:
  - tag: component
    value: network
- name: Get status
  key: apache.get_status
  interval: 1m
  type: http_agent
  value_type: text
  description: "Getting data from a machine-readable version of the Apache status\
    \ page.\r\nFor more information see Apache Module [mod_status](https://httpd.apache.org/docs/current/mod/mod_status.html)."
  history: 1h
  trends: '0'
  tags:
  - tag: component
    value: raw
- name: Total requests
  key: apache.requests
  interval: '0'
  type: dependent
  master_item_key: apache.get_status
  value_type: unsigned
  description: The total number of the Apache server accesses.
  history: 31d
  tags:
  - tag: component
    value: network
- name: Requests per second
  key: apache.requests.rate
  interval: '0'
  type: dependent
  master_item_key: apache.get_status
  description: "It is calculated as a rate of change for the \"Total requests\" statistics.\r\
    \n`ReqPerSec` is not used, as it counts the average since the last Apache server\
    \ start."
  history: 31d
  tags:
  - tag: component
    value: network
- name: Uptime
  key: apache.uptime
  interval: '0'
  type: dependent
  master_item_key: apache.get_status
  value_type: unsigned
  units: uptime
  description: The service uptime expressed in seconds.
  history: 31d
  tags:
  - tag: component
    value: system
- name: Version
  key: apache.version
  interval: '0'
  type: dependent
  master_item_key: apache.get_status
  value_type: char
  description: The Apache service version.
  history: 31d
  trends: '0'
  tags:
  - tag: component
    value: system
- name: Workers idle cleanup
  key: apache.workers.cleanup
  interval: '0'
  type: dependent
  master_item_key: apache.get_status
  value_type: unsigned
  description: The number of workers in cleanup state.
  history: 31d
  tags:
  - tag: component
    value: system
- name: Workers closing connection
  key: apache.workers.closing
  interval: '0'
  type: dependent
  master_item_key: apache.get_status
  value_type: unsigned
  description: The number of workers in closing state.
  history: 31d
  tags:
  - tag: component
    value: system
- name: Workers DNS lookup
  key: apache.workers.dnslookup
  interval: '0'
  type: dependent
  master_item_key: apache.get_status
  value_type: unsigned
  description: The number of workers in `dnslookup` state.
  history: 31d
  tags:
  - tag: component
    value: system
- name: Workers finishing
  key: apache.workers.finishing
  interval: '0'
  type: dependent
  master_item_key: apache.get_status
  value_type: unsigned
  description: The number of workers in finishing state.
  history: 31d
  tags:
  - tag: component
    value: system
- name: Workers keepalive (read)
  key: apache.workers.keepalive
  interval: '0'
  type: dependent
  master_item_key: apache.get_status
  value_type: unsigned
  description: The number of workers in `keepalive` state.
  history: 31d
  tags:
  - tag: component
    value: system
- name: Workers logging
  key: apache.workers.logging
  interval: '0'
  type: dependent
  master_item_key: apache.get_status
  value_type: unsigned
  description: The number of workers in logging state.
  history: 31d
  tags:
  - tag: component
    value: system
- name: Workers reading request
  key: apache.workers.reading
  interval: '0'
  type: dependent
  master_item_key: apache.get_status
  value_type: unsigned
  description: The number of workers in reading state.
  history: 31d
  tags:
  - tag: component
    value: system
- name: Workers sending reply
  key: apache.workers.sending
  interval: '0'
  type: dependent
  master_item_key: apache.get_status
  value_type: unsigned
  description: The number of workers in sending state.
  history: 31d
  tags:
  - tag: component
    value: system
- name: Workers slot with no current process
  key: apache.workers.slot
  interval: '0'
  type: dependent
  master_item_key: apache.get_status
  value_type: unsigned
  description: The number of slots with no current process.
  history: 31d
  tags:
  - tag: component
    value: system
- name: Workers starting up
  key: apache.workers.starting
  interval: '0'
  type: dependent
  master_item_key: apache.get_status
  value_type: unsigned
  description: The number of workers in starting state.
  history: 31d
  tags:
  - tag: component
    value: system
- name: Workers waiting for connection
  key: apache.workers.waiting
  interval: '0'
  type: dependent
  master_item_key: apache.get_status
  value_type: unsigned
  description: The number of workers in waiting state.
  history: 31d
  tags:
  - tag: component
    value: system
- name: Total workers busy
  key: apache.workers_total.busy
  interval: '0'
  type: dependent
  master_item_key: apache.get_status
  value_type: unsigned
  description: The total number of busy worker threads/processes.
  history: 31d
  tags:
  - tag: component
    value: system
- name: Total workers idle
  key: apache.workers_total.idle
  interval: '0'
  type: dependent
  master_item_key: apache.get_status
  value_type: unsigned
  description: The total number of idle worker threads/processes.
  history: 31d
  tags:
  - tag: component
    value: system
- name: Service response time
  key: net.tcp.service.perf[http,"{$APACHE.STATUS.HOST}","{$APACHE.STATUS.PORT}"]
  interval: 1m
  type: simple_check
  units: s
  history: 31d
  tags:
  - tag: component
    value: application
  - tag: component
    value: health
- name: Service ping
  key: net.tcp.service[http,"{$APACHE.STATUS.HOST}","{$APACHE.STATUS.PORT}"]
  interval: 1m
  type: simple_check
  value_type: unsigned
  history: 31d
  tags:
  - tag: component
    value: application
  - tag: component
    value: health
triggers:
- name: 'Apache: Failed to fetch status page'
  expression: nodata(/Apache by HTTP/apache.get_status,30m)=1
  severity: warning
  description: Zabbix has not received any data for items for the last 30 minutes.
  tags:
  - tag: scope
    value: availability
- name: 'Apache: Service has been restarted'
  expression: last(/Apache by HTTP/apache.uptime)<10m
  severity: information
  description: Uptime is less than 10 minutes.
  tags:
  - tag: scope
    value: notice
- name: 'Apache: Version has changed'
  expression: last(/Apache by HTTP/apache.version,#1)<>last(/Apache by HTTP/apache.version,#2)
    and length(last(/Apache by HTTP/apache.version))>0
  severity: information
  description: Apache version has changed. Acknowledge to close the problem manually.
  tags:
  - tag: scope
    value: notice
- name: 'Apache: Service response time is too high'
  expression: min(/Apache by HTTP/net.tcp.service.perf[http,"","80"],5m)>10
  severity: warning
  tags:
  - tag: scope
    value: performance
- name: 'Apache: Service is down'
  expression: last(/Apache by HTTP/net.tcp.service[http,"","80"])=0
  severity: average
  tags:
  - tag: scope
    value: availability
discovery_rules:
- name: Event MPM discovery
  key: apache.mpm.event.discovery
  interval: '0'
  type: dependent
  master_item_key: apache.get_status
  item_prototypes:
  - name: Bytes per request
    key: apache.bytes[per_request{#SINGLETON}]
    interval: '0'
    type: dependent
    units: B
  - name: Connections async closing
    key: apache.connections[async_closing{#SINGLETON}]
    interval: '0'
    type: dependent
    value_type: unsigned
  - name: Connections async keepalive
    key: apache.connections[async_keep_alive{#SINGLETON}]
    interval: '0'
    type: dependent
    value_type: unsigned
  - name: Connections async writing
    key: apache.connections[async_writing{#SINGLETON}]
    interval: '0'
    type: dependent
    value_type: unsigned
  - name: Connections total
    key: apache.connections[total{#SINGLETON}]
    interval: '0'
    type: dependent
    value_type: unsigned
  - name: Number of async processes
    key: apache.process[num{#SINGLETON}]
    interval: '0'
    type: dependent
    value_type: unsigned
