template: Asterisk by HTTP
description: "The template gets Asterisk metrics from AMI by HTTP agent.\r\nYou should\
  \ enable the mini-HTTP Server, add the option webenabled=yes in the general section\
  \ of the manager.conf file and create Asterisk Manager user with system and command\
  \ write permissions within your Asterisk instance.\r\nDisable the PJSIP driver if\
  \ you do not use PJSIP or do not have PJSIP endpoints.\r\nPlease, define AMI address\
  \ in the {$AMI.URL} macro. Also, set the hostname or IP address of the AMI host\
  \ in the {$AMI.HOST} macro for Zabbix to check Asterisk service status.\r\nThen\
  \ you can define {$AMI.USERNAME} and {$AMI.SECRET} macros in the template for using\
  \ on the host level.\r\nIf there are errors, increase the logging to debug level\
  \ and see the Zabbix server log.\r\n\r\nYou can discuss this template or leave feedback\
  \ on our forum https://www.zabbix.com/forum/zabbix-suggestions-and-feedback/410060-discussion-thread-for-official-zabbix-template-asterisk\r\
  \n\r\nGenerated by official Zabbix template tool \"Templator\""
groups:
- Templates
items:
- name: Active calls
  key: asterisk.active_calls
  interval: '0'
  type: dependent
  master_item_key: asterisk.get_stats
  value_type: unsigned
  description: The number of active calls at the moment.
  history: 31d
  tags:
  - tag: component
    value: calls
- name: Active channels
  key: asterisk.active_channels
  interval: '0'
  type: dependent
  master_item_key: asterisk.get_stats
  value_type: unsigned
  description: The number of active channels at the moment.
  history: 31d
  tags:
  - tag: component
    value: channels
- name: Calls processed
  key: asterisk.calls_processed
  interval: '0'
  type: dependent
  master_item_key: asterisk.get_stats
  value_type: unsigned
  description: The number of calls processed after the last service restart.
  history: 31d
  tags:
  - tag: component
    value: calls
- name: Calls processed per second
  key: asterisk.calls_processed.rate
  interval: '0'
  type: dependent
  master_item_key: asterisk.get_stats
  description: The number of calls processed per second.
  history: 31d
  tags:
  - tag: component
    value: calls
- name: Get stats
  key: asterisk.get_stats
  interval: 1m
  type: http_agent
  value_type: text
  description: Asterisk system information in JSON format.
  history: '0'
  trends: '0'
  tags:
  - tag: component
    value: raw
- name: IAX trunks active channels
  key: asterisk.iax.active_channels
  interval: '0'
  type: dependent
  master_item_key: asterisk.get_stats
  value_type: unsigned
  description: The total number of IAX trunks active channels.
  history: 31d
  tags:
  - tag: component
    value: channels
- name: IAX offline peers
  key: asterisk.iax.offline
  interval: '0'
  type: dependent
  master_item_key: asterisk.get_stats
  value_type: unsigned
  description: The number of offline IAX peers.
  history: 31d
  tags:
  - tag: component
    value: peers
- name: IAX online peers
  key: asterisk.iax.online
  interval: '0'
  type: dependent
  master_item_key: asterisk.get_stats
  value_type: unsigned
  description: The number of online IAX peers.
  history: 31d
  tags:
  - tag: component
    value: peers
- name: IAX peers
  key: asterisk.iax.total
  interval: '0'
  type: dependent
  master_item_key: asterisk.get_stats
  value_type: unsigned
  description: The total number of IAX peers.
  history: 31d
  tags:
  - tag: component
    value: peers
- name: IAX unmonitored peers
  key: asterisk.iax.unmonitored
  interval: '0'
  type: dependent
  master_item_key: asterisk.get_stats
  value_type: unsigned
  description: The number of unmonitored IAX peers.
  history: 31d
  tags:
  - tag: component
    value: peers
- name: PJSIP trunks active channels
  key: asterisk.pjsip.active_channels
  interval: '0'
  type: dependent
  master_item_key: asterisk.get_stats
  value_type: unsigned
  description: The total number of PJSIP trunks active channels.
  history: 31d
  tags:
  - tag: component
    value: channels
- name: PJSIP available endpoints
  key: asterisk.pjsip.available
  interval: '0'
  type: dependent
  master_item_key: asterisk.get_stats
  value_type: unsigned
  description: The number of available PJSIP peers.
  history: 31d
  tags:
  - tag: component
    value: peers
- name: PJSIP endpoints
  key: asterisk.pjsip.total
  interval: '0'
  type: dependent
  master_item_key: asterisk.get_stats
  value_type: unsigned
  description: The total number of PJSIP peers.
  history: 31d
  tags:
  - tag: component
    value: peers
- name: PJSIP unavailable endpoints
  key: asterisk.pjsip.unavailable
  interval: '0'
  type: dependent
  master_item_key: asterisk.get_stats
  value_type: unsigned
  description: The number of unavailable PJSIP peers.
  history: 31d
  tags:
  - tag: component
    value: peers
- name: SIP trunks active channels
  key: asterisk.sip.active_channels
  interval: '0'
  type: dependent
  master_item_key: asterisk.get_stats
  value_type: unsigned
  description: The total number of SIP trunks active channels.
  history: 31d
  tags:
  - tag: component
    value: channels
- name: SIP monitored offline
  key: asterisk.sip.monitored_offline
  interval: '0'
  type: dependent
  master_item_key: asterisk.get_stats
  value_type: unsigned
  description: The number of monitored offline SIP peers.
  history: 31d
  tags:
  - tag: component
    value: peers
- name: SIP monitored online
  key: asterisk.sip.monitored_online
  interval: '0'
  type: dependent
  master_item_key: asterisk.get_stats
  value_type: unsigned
  description: The number of monitored online SIP peers.
  history: 31d
  tags:
  - tag: component
    value: peers
- name: SIP peers
  key: asterisk.sip.total
  interval: '0'
  type: dependent
  master_item_key: asterisk.get_stats
  value_type: unsigned
  description: The total number of SIP peers.
  history: 31d
  tags:
  - tag: component
    value: peers
- name: SIP unmonitored offline
  key: asterisk.sip.unmonitored_offline
  interval: '0'
  type: dependent
  master_item_key: asterisk.get_stats
  value_type: unsigned
  description: The number of unmonitored offline SIP peers.
  history: 31d
  tags:
  - tag: component
    value: peers
- name: SIP unmonitored online
  key: asterisk.sip.unmonitored_online
  interval: '0'
  type: dependent
  master_item_key: asterisk.get_stats
  value_type: unsigned
  description: The number of unmonitored online SIP peers.
  history: 31d
  tags:
  - tag: component
    value: peers
- name: Total queues
  key: asterisk.total_queues
  interval: '0'
  type: dependent
  master_item_key: asterisk.get_stats
  value_type: unsigned
  description: The number of configured queues.
  history: 31d
  tags:
  - tag: component
    value: queues
- name: Uptime
  key: asterisk.uptime
  interval: '0'
  type: dependent
  master_item_key: asterisk.get_stats
  units: uptime
  description: 'The system uptime expressed in the following format: "N days, hh:mm:ss".'
  history: 31d
  tags:
  - tag: component
    value: system
- name: Uptime after reload
  key: asterisk.uptime_reload
  interval: '0'
  type: dependent
  master_item_key: asterisk.get_stats
  units: uptime
  description: System uptime after a config reload in 'N days, hh:mm:ss' format.
  history: 31d
  tags:
  - tag: component
    value: system
- name: Version
  key: asterisk.version
  interval: '0'
  type: dependent
  master_item_key: asterisk.get_stats
  value_type: char
  description: Service version
  history: 31d
  trends: '0'
  tags:
  - tag: component
    value: application
- name: Service response time
  key: net.tcp.service.perf["tcp","{$AMI.HOST}","{$AMI.PORT}"]
  interval: 1m
  type: simple_check
  units: s
  description: Asterisk Manager API performance.
  history: 31d
  tags:
  - tag: component
    value: network
- name: Service status
  key: net.tcp.service["tcp","{$AMI.HOST}","{$AMI.PORT}"]
  interval: 1m
  type: simple_check
  value_type: unsigned
  description: Asterisk Manager API port availability.
  history: 31d
  tags:
  - tag: component
    value: health
  - tag: component
    value: network
triggers:
- name: 'Asterisk: Total number of active channels of IAX trunks is too high'
  expression: min(/Asterisk by HTTP/asterisk.iax.active_channels,10m)>=28
  severity: warning
  description: The IAX trunks may not be able to process new calls.
  tags:
  - tag: scope
    value: performance
- name: 'Asterisk: Total number of active channels of PJSIP trunks is too high'
  expression: min(/Asterisk by HTTP/asterisk.pjsip.active_channels,10m)>=28
  severity: warning
  description: The PJSIP trunks may not be able to process new calls.
  tags:
  - tag: scope
    value: performance
- name: 'Asterisk: Total number of active channels of SIP trunks is too high'
  expression: min(/Asterisk by HTTP/asterisk.sip.active_channels,10m)>=28
  severity: warning
  description: The SIP trunks may not be able to process new calls.
  tags:
  - tag: scope
    value: performance
- name: 'Asterisk: Service has been restarted'
  expression: last(/Asterisk by HTTP/asterisk.uptime)<10m
  severity: information
  description: Uptime is less than 10 minutes.
  tags:
  - tag: scope
    value: notice
- name: 'Asterisk: Failed to fetch AMI page'
  expression: nodata(/Asterisk by HTTP/asterisk.uptime,30m)=1
  severity: warning
  description: Zabbix has not received any data for items for the last 30 minutes.
  tags:
  - tag: scope
    value: availability
- name: 'Asterisk: Configuration has been reloaded'
  expression: last(/Asterisk by HTTP/asterisk.uptime_reload)<10m
  severity: information
  description: Uptime is less than 10 minutes.
  tags:
  - tag: scope
    value: notice
- name: 'Asterisk: Version has changed'
  expression: last(/Asterisk by HTTP/asterisk.version,#1)<>last(/Asterisk by HTTP/asterisk.version,#2)
    and length(last(/Asterisk by HTTP/asterisk.version))>0
  severity: information
  description: The Asterisk version has changed. Acknowledge to close the problem
    manually.
  tags:
  - tag: scope
    value: notice
- name: 'Asterisk: Service response time is too high'
  expression: min(/Asterisk by HTTP/net.tcp.service.perf["tcp","<SET AMI HOST>","5038"],5m)>10s
  severity: warning
  tags:
  - tag: scope
    value: performance
- name: 'Asterisk: Service is down'
  expression: last(/Asterisk by HTTP/net.tcp.service["tcp","<SET AMI HOST>","5038"])=0
  severity: average
  tags:
  - tag: scope
    value: availability
discovery_rules:
- name: IAX peers discovery
  key: asterisk.iax_peers.discovery
  interval: '0'
  type: dependent
  master_item_key: asterisk.get_stats
  item_prototypes:
  - name: 'IAX trunk "{#OBJECTNAME}": Get IAX trunk'
    key: asterisk.iax.trunk.get[{#OBJECTNAME}]
    interval: '0'
    type: dependent
    value_type: text
  - name: 'IAX trunk "{#OBJECTNAME}": Active channels'
    key: asterisk.iax.trunk.active_channels[{#OBJECTNAME}]
    interval: '0'
    type: dependent
    master_item_key: asterisk.iax.trunk.get[{#OBJECTNAME}]
    value_type: unsigned
  - name: 'IAX trunk "{#OBJECTNAME}": Status'
    key: asterisk.iax.trunk.status[{#OBJECTNAME}]
    interval: '0'
    type: dependent
    master_item_key: asterisk.iax.trunk.get[{#OBJECTNAME}]
    value_type: char
  trigger_prototypes:
  - name: 'Asterisk: IAX trunk "{#OBJECTNAME}": Number of the IAX trunk "{#OBJECTNAME}"
      active channels is too high'
    expression: min(/Asterisk by HTTP/asterisk.iax.trunk.active_channels[{#OBJECTNAME}],10m)>=28
    severity: warning
  - name: 'Asterisk: IAX trunk "{#OBJECTNAME}": IAX trunk {#OBJECTNAME} has a state
      {ITEM.VALUE}'
    expression: last(/Asterisk by HTTP/asterisk.iax.trunk.status[{#OBJECTNAME}])="UNKNOWN"
      or last(/Asterisk by HTTP/asterisk.iax.trunk.status[{#OBJECTNAME}])="UNREACHABLE"
    severity: average
- name: PJSIP endpoints discovery
  key: asterisk.pjsip_endpoints.discovery
  interval: '0'
  type: dependent
  master_item_key: asterisk.get_stats
  item_prototypes:
  - name: 'PJSIP trunk "{#OBJECTNAME}": Get PJSIP trunk'
    key: asterisk.pjsip.trunk.get[{#OBJECTNAME}]
    interval: '0'
    type: dependent
    value_type: text
  - name: 'PJSIP trunk "{#OBJECTNAME}": Active channels'
    key: asterisk.pjsip.trunk.active_channels[{#OBJECTNAME}]
    interval: '0'
    type: dependent
    master_item_key: asterisk.pjsip.trunk.get[{#OBJECTNAME}]
    value_type: unsigned
  - name: 'PJSIP trunk "{#OBJECTNAME}": Device state'
    key: asterisk.pjsip.trunk.devicestate[{#OBJECTNAME}]
    interval: '0'
    type: dependent
    master_item_key: asterisk.pjsip.trunk.get[{#OBJECTNAME}]
    value_type: char
  trigger_prototypes:
  - name: 'Asterisk: PJSIP trunk "{#OBJECTNAME}": Number of the PJSIP trunk "{#OBJECTNAME}"
      active channels is too high'
    expression: min(/Asterisk by HTTP/asterisk.pjsip.trunk.active_channels[{#OBJECTNAME}],10m)>=28
    severity: warning
  - name: 'Asterisk: PJSIP trunk "{#OBJECTNAME}": PJSIP trunk {#OBJECTNAME} has a
      state Unavailable'
    expression: last(/Asterisk by HTTP/asterisk.pjsip.trunk.devicestate[{#OBJECTNAME}])="Unavailable"
    severity: average
- name: Queues discovery
  key: asterisk.queues.discovery
  interval: '0'
  type: dependent
  master_item_key: asterisk.get_stats
  item_prototypes:
  - name: '"{#QUEUE}": Get queue'
    key: asterisk.queue.get[{#QUEUE}]
    interval: '0'
    type: dependent
    value_type: text
  - name: '"{#QUEUE}": Available'
    key: asterisk.queue.available[{#QUEUE}]
    interval: '0'
    type: dependent
    master_item_key: asterisk.queue.get[{#QUEUE}]
    value_type: unsigned
  - name: '"{#QUEUE}": Callers'
    key: asterisk.queue.callers[{#QUEUE}]
    interval: '0'
    type: dependent
    master_item_key: asterisk.queue.get[{#QUEUE}]
    value_type: unsigned
  - name: '"{#QUEUE}": Logged in'
    key: asterisk.queue.loggedin[{#QUEUE}]
    interval: '0'
    type: dependent
    master_item_key: asterisk.queue.get[{#QUEUE}]
    value_type: unsigned
  trigger_prototypes:
  - name: 'Asterisk: "{#QUEUE}": Number of callers in the queue "{#QUEUE}" is too
      high'
    expression: min(/Asterisk by HTTP/asterisk.queue.callers[{#QUEUE}],10m)>10
    severity: warning
- name: SIP peers discovery
  key: asterisk.sip_peers.discovery
  interval: '0'
  type: dependent
  master_item_key: asterisk.get_stats
  item_prototypes:
  - name: 'SIP trunk "{#OBJECTNAME}": Get SIP trunk'
    key: asterisk.sip.trunk.get[{#OBJECTNAME}]
    interval: '0'
    type: dependent
    value_type: text
  - name: 'SIP trunk "{#OBJECTNAME}": Active channels'
    key: asterisk.sip.trunk.active_channels[{#OBJECTNAME}]
    interval: '0'
    type: dependent
    master_item_key: asterisk.sip.trunk.get[{#OBJECTNAME}]
    value_type: unsigned
  - name: 'SIP trunk "{#OBJECTNAME}": Status'
    key: asterisk.sip.trunk.status[{#OBJECTNAME}]
    interval: '0'
    type: dependent
    master_item_key: asterisk.sip.trunk.get[{#OBJECTNAME}]
    value_type: char
  trigger_prototypes:
  - name: 'Asterisk: SIP trunk "{#OBJECTNAME}": Number of the SIP trunk "{#OBJECTNAME}"
      active channels is too high'
    expression: min(/Asterisk by HTTP/asterisk.sip.trunk.active_channels[{#OBJECTNAME}],10m)>=28
    severity: warning
  - name: 'Asterisk: SIP trunk "{#OBJECTNAME}": SIP trunk {#OBJECTNAME} has a state
      {ITEM.VALUE}'
    expression: last(/Asterisk by HTTP/asterisk.sip.trunk.status[{#OBJECTNAME}])="UNKNOWN"
      or last(/Asterisk by HTTP/asterisk.sip.trunk.status[{#OBJECTNAME}])="UNREACHABLE"
    severity: average
