template: Nginx by HTTP
description: "This template is developed to monitor Nginx by Zabbix that works without\
  \ any external scripts.\r\nMost of the metrics are collected in one go, thanks to\
  \ Zabbix bulk data collection.\r\n\r\nThe template collects metrics by polling the\
  \ module 'ngx_http_stub_status_module' with HTTP agent remotely:\r\nhttps://nginx.ru/en/docs/http/ngx_http_stub_status_module.html\r\
  \n\r\nActive connections: 291\r\nserver accepts handled requests\r\n16630948 16630948\
  \ 31070465\r\nReading: 6 Writing: 179 Waiting: 106\r\n\r\nSetup:\r\n\r\n1. See the\
  \ setup instructions for 'ngx_http_stub_status_module':\r\nhttps://nginx.ru/en/docs/http/ngx_http_stub_status_module.html\r\
  \n\r\nTest the availability of the 'http_stub_status_module' with 'nginx -V 2>&1\
  \ | grep -o with-http_stub_status_module'.\r\n\r\nExample configuration of Nginx:\r\
  \n\r\nlocation = /basic_status {\r\n    stub_status;\r\n    allow <IP of your Zabbix\
  \ server/proxy>;\r\n    deny all;\r\n}\r\n\r\n2. Set the hostname or IP address\
  \ of the Nginx host or Nginx container in the '{$NGINX.STUB_STATUS.HOST}' macro.\
  \ You can also change the status page port in the '{$NGINX.STUB_STATUS.PORT}' macro,\
  \ the status page scheme in the '{$NGINX.STUB_STATUS.SCHEME}' macro and the status\
  \ page path in the '{$NGINX.STUB_STATUS.PATH}' macro if necessary.\r\n\r\nYou can\
  \ discuss this template or leave feedback on our forum https://www.zabbix.com/forum/zabbix-suggestions-and-feedback/384765-discussion-thread-for-official-zabbix-template-nginx\r\
  \n\r\nGenerated by official Zabbix template tool \"Templator\""
groups:
- Templates
items:
- name: Service response time
  key: net.tcp.service.perf[http,"{$NGINX.STUB_STATUS.HOST}","{$NGINX.STUB_STATUS.PORT}"]
  interval: 1m
  type: simple_check
  units: s
  history: 31d
  tags:
  - tag: component
    value: application
  - tag: component
    value: health
- name: Service status
  key: net.tcp.service[http,"{$NGINX.STUB_STATUS.HOST}","{$NGINX.STUB_STATUS.PORT}"]
  interval: 1m
  type: simple_check
  value_type: unsigned
  history: 31d
  tags:
  - tag: component
    value: application
  - tag: component
    value: health
- name: Connections accepted per second
  key: nginx.connections.accepted.rate
  interval: '0'
  type: dependent
  master_item_key: nginx.get_stub_status
  description: The total number of accepted client connections.
  history: 31d
  tags:
  - tag: component
    value: connections
- name: Connections active
  key: nginx.connections.active
  interval: '0'
  type: dependent
  master_item_key: nginx.get_stub_status
  value_type: unsigned
  description: The current number of active client connections including waiting connections.
  history: 31d
  tags:
  - tag: component
    value: connections
- name: Connections dropped per second
  key: nginx.connections.dropped.rate
  interval: '0'
  type: dependent
  master_item_key: nginx.get_stub_status
  description: The total number of dropped client connections.
  history: 31d
  tags:
  - tag: component
    value: connections
- name: Connections handled per second
  key: nginx.connections.handled.rate
  interval: '0'
  type: dependent
  master_item_key: nginx.get_stub_status
  description: The total number of handled connections. Generally, the parameter value
    is the same as for the accepted connections, unless some resource limits have
    been reached (for example, the `worker_connections limit`).
  history: 31d
  tags:
  - tag: component
    value: connections
- name: Connections reading
  key: nginx.connections.reading
  interval: '0'
  type: dependent
  master_item_key: nginx.get_stub_status
  value_type: unsigned
  description: The current number of connections where Nginx is reading the request
    header.
  history: 31d
  tags:
  - tag: component
    value: connections
- name: Connections waiting
  key: nginx.connections.waiting
  interval: '0'
  type: dependent
  master_item_key: nginx.get_stub_status
  value_type: unsigned
  description: The current number of idle client connections waiting for a request.
  history: 31d
  tags:
  - tag: component
    value: connections
- name: Connections writing
  key: nginx.connections.writing
  interval: '0'
  type: dependent
  master_item_key: nginx.get_stub_status
  value_type: unsigned
  description: The current number of connections where Nginx is writing a response
    back to the client.
  history: 31d
  tags:
  - tag: component
    value: connections
- name: Get stub status page
  key: nginx.get_stub_status
  interval: 1m
  type: http_agent
  value_type: text
  description: "The following status information is provided:\r\n`Active connections`\
    \ - the current number of active client connections including waiting connections.\r\
    \n`Accepted` - the total number of accepted client connections.\r\n`Handled` -\
    \ the total number of handled connections. Generally, the parameter value is the\
    \ same as for the accepted connections, unless some resource limits have been\
    \ reached (for example, the `worker_connections` limit).\r\n`Requests` - the total\
    \ number of client requests.\r\n`Reading` - the current number of connections\
    \ where Nginx is reading the request header.\r\n`Writing` - the current number\
    \ of connections where Nginx is writing a response back to the client.\r\n`Waiting`\
    \ - the current number of idle client connections waiting for a request.\r\n\r\
    \nSee also [Module ngx_http_stub_status_module](https://nginx.org/en/docs/http/ngx_http_stub_status_module.html)."
  history: 1h
  trends: '0'
  tags:
  - tag: component
    value: application
  - tag: component
    value: health
- name: Requests total
  key: nginx.requests.total
  interval: '0'
  type: dependent
  master_item_key: nginx.get_stub_status
  value_type: unsigned
  description: The total number of client requests.
  history: 31d
  tags:
  - tag: component
    value: requests
- name: Requests per second
  key: nginx.requests.total.rate
  interval: '0'
  type: dependent
  master_item_key: nginx.get_stub_status
  description: The total number of client requests.
  history: 31d
  tags:
  - tag: component
    value: requests
- name: Version
  key: nginx.version
  interval: '0'
  type: dependent
  master_item_key: nginx.get_stub_status
  value_type: char
  history: 31d
  trends: '0'
  tags:
  - tag: component
    value: application
triggers:
- name: 'Nginx: Service response time is too high'
  expression: min(/Nginx by HTTP/net.tcp.service.perf[http,"","80"],5m)>10
  severity: warning
  tags:
  - tag: scope
    value: performance
- name: 'Nginx: Service is down'
  expression: last(/Nginx by HTTP/net.tcp.service[http,"","80"])=0
  severity: average
  tags:
  - tag: scope
    value: availability
- name: 'Nginx: High connections drop rate'
  expression: min(/Nginx by HTTP/nginx.connections.dropped.rate,5m) > 1
  severity: warning
  description: The rate of dropping connections has been greater than {$NGINX.DROP_RATE.MAX.WARN}
    for the last 5 minutes.
  tags:
  - tag: scope
    value: performance
- name: 'Nginx: Failed to fetch stub status page'
  expression: "find(/Nginx by HTTP/nginx.get_stub_status,,\"iregexp\",\"HTTP\\\\/[\\\
    \\d.]+\\\\s+200\")=0 or\r\nnodata(/Nginx by HTTP/nginx.get_stub_status,30m)=1"
  severity: warning
  description: Zabbix has not received any data for items for the last 30 minutes.
  tags:
  - tag: scope
    value: availability
- name: 'Nginx: Version has changed'
  expression: last(/Nginx by HTTP/nginx.version,#1)<>last(/Nginx by HTTP/nginx.version,#2)
    and length(last(/Nginx by HTTP/nginx.version))>0
  severity: information
  description: The Nginx version has changed. Acknowledge to close the problem manually.
  tags:
  - tag: scope
    value: notice
