template: RabbitMQ node by HTTP
description: "This template is developed to monitor the messaging broker RabbitMQ\
  \ node by Zabbix that works without any external scripts.\r\nMost of the metrics\
  \ are collected in one go, thanks to Zabbix bulk data collection.\r\n\r\nThe template\
  \ collects metrics by polling RabbitMQ management plugin with HTTP agent remotely.\r\
  \n\r\nSetup:\r\n\r\n1. Enable the RabbitMQ management plugin. See the RabbitMQ documentation\
  \ for the instructions:\r\nhttps://www.rabbitmq.com/management.html\r\n\r\n2. Create\
  \ a user to monitor the service:\r\n\r\nrabbitmqctl add_user zbx_monitor <PASSWORD>\r\
  \nrabbitmqctl set_permissions  -p / zbx_monitor \"\" \"\" \".*\"\r\nrabbitmqctl\
  \ set_user_tags zbx_monitor monitoring\r\n\r\n3. Set the hostname or IP address\
  \ of the RabbitMQ node host in the '{$RABBITMQ.API.HOST}' macro. You can also change\
  \ the port in the '{$RABBITMQ.API.PORT}' macro and the scheme in the '{$RABBITMQ.API.SCHEME}'\
  \ macro if necessary.\r\n\r\n4. Set the user name and password in the macros '{$RABBITMQ.API.USER}'\
  \ and '{$RABBITMQ.API.PASSWORD}'.\r\n\r\nYou can discuss this template or leave\
  \ feedback on our forum https://www.zabbix.com/forum/zabbix-suggestions-and-feedback/387226-discussion-thread-for-official-zabbix-template-rabbitmq\r\
  \n\r\nGenerated by official Zabbix template tool \"Templator\""
groups:
- Templates
items:
- name: Service response time
  key: net.tcp.service.perf["{$RABBITMQ.API.SCHEME}","{$RABBITMQ.API.HOST}","{$RABBITMQ.API.PORT}"]
  interval: 1m
  type: simple_check
  units: s
  history: 31d
  tags:
  - tag: component
    value: system
- name: Service ping
  key: net.tcp.service["{$RABBITMQ.API.SCHEME}","{$RABBITMQ.API.HOST}","{$RABBITMQ.API.PORT}"]
  interval: 1m
  type: simple_check
  value_type: unsigned
  history: 31d
  tags:
  - tag: component
    value: health
  - tag: component
    value: network
- name: Get node overview
  key: rabbitmq.get_node_overview
  interval: 1m
  type: http_agent
  value_type: text
  description: The HTTP API endpoint that returns cluster-wide metrics.
  history: 1h
  trends: '0'
  tags:
  - tag: component
    value: raw
- name: Get nodes
  key: rabbitmq.get_nodes
  interval: 1m
  type: http_agent
  value_type: text
  description: The HTTP API endpoint that returns metrics of the nodes.
  history: 1h
  trends: '0'
  tags:
  - tag: component
    value: raw
- name: Get queues
  key: rabbitmq.get_queues
  interval: 1m
  type: http_agent
  value_type: text
  description: The HTTP API endpoint that returns metrics of the queues metrics.
  history: 1h
  trends: '0'
  tags:
  - tag: component
    value: raw
- name: Free disk space
  key: rabbitmq.node.disk_free
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_nodes
  value_type: unsigned
  units: B
  description: The current free disk space.
  history: 31d
  tags:
  - tag: component
    value: storage
- name: Disk free alarm
  key: rabbitmq.node.disk_free_alarm
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_nodes
  value_type: unsigned
  description: It checks whether the node has a disk alarm or not.
  history: 31d
  tags:
  - tag: component
    value: storage
- name: Disk free limit
  key: rabbitmq.node.disk_free_limit
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_nodes
  value_type: unsigned
  units: B
  description: The free space limit of a disk expressed in bytes.
  history: 31d
  tags:
  - tag: component
    value: storage
- name: Used file descriptors
  key: rabbitmq.node.fd_used
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_nodes
  value_type: unsigned
  description: The descriptors of the used file.
  history: 31d
  tags:
  - tag: component
    value: storage
- name: Memory alarm
  key: rabbitmq.node.mem_alarm
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_nodes
  value_type: unsigned
  description: It checks whether the host has a memory alarm or not.
  history: 31d
  tags:
  - tag: component
    value: memory
- name: Memory limit
  key: rabbitmq.node.mem_limit
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_nodes
  value_type: unsigned
  units: B
  description: The memory usage with high watermark properties expressed in bytes.
  history: 31d
  tags:
  - tag: component
    value: memory
- name: Memory used
  key: rabbitmq.node.mem_used
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_nodes
  value_type: unsigned
  units: B
  description: The memory usage expressed in bytes.
  history: 31d
  tags:
  - tag: component
    value: memory
- name: Management plugin version
  key: rabbitmq.node.overview.management_version
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_node_overview
  value_type: char
  description: The version of the management plugin in use.
  history: 31d
  trends: '0'
  tags:
  - tag: component
    value: system
- name: RabbitMQ version
  key: rabbitmq.node.overview.rabbitmq_version
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_node_overview
  value_type: char
  description: The version of the RabbitMQ on the node, which processed this request.
  history: 31d
  trends: '0'
  tags:
  - tag: component
    value: system
- name: Number of network partitions
  key: rabbitmq.node.partitions
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_nodes
  value_type: unsigned
  description: The number of network partitions, which this node "sees".
  history: 31d
  tags:
  - tag: component
    value: network
- name: Runtime run queue
  key: rabbitmq.node.run_queue
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_nodes
  value_type: unsigned
  description: The average number of Erlang processes waiting to run.
  history: 31d
  tags:
  - tag: component
    value: system
- name: Is running
  key: rabbitmq.node.running
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_nodes
  value_type: unsigned
  description: It "sees" whether the node is running or not.
  history: 31d
  tags:
  - tag: component
    value: system
- name: Sockets available
  key: rabbitmq.node.sockets_total
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_nodes
  value_type: unsigned
  description: The file descriptors available for use as sockets.
  history: 31d
  tags:
  - tag: component
    value: system
- name: Sockets used
  key: rabbitmq.node.sockets_used
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_nodes
  value_type: unsigned
  description: The number of file descriptors used as sockets.
  history: 31d
  tags:
  - tag: component
    value: system
- name: Uptime
  key: rabbitmq.node.uptime
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_nodes
  units: s
  description: Uptime expressed in milliseconds.
  history: 31d
  tags:
  - tag: component
    value: system
triggers:
- name: 'RabbitMQ node: Service response time is too high'
  expression: min(/RabbitMQ node by HTTP/net.tcp.service.perf["http","<SET NODE API
    HOST>","15672"],5m)>10
  severity: warning
  tags:
  - tag: scope
    value: performance
- name: 'RabbitMQ node: Service is down'
  expression: last(/RabbitMQ node by HTTP/net.tcp.service["http","<SET NODE API HOST>","15672"])=0
  severity: average
  tags:
  - tag: scope
    value: availability
- name: 'RabbitMQ node: Failed to fetch nodes data'
  expression: nodata(/RabbitMQ node by HTTP/rabbitmq.get_nodes,30m)=1
  severity: warning
  description: Zabbix has not received any data for items for the last 30 minutes.
  tags:
  - tag: scope
    value: availability
- name: 'RabbitMQ node: Free disk space alarm'
  expression: last(/RabbitMQ node by HTTP/rabbitmq.node.disk_free_alarm)=1
  severity: average
  description: For more details see [Free Disk Space Alarms](https://www.rabbitmq.com/disk-alarms.html).
  tags:
  - tag: scope
    value: performance
- name: 'RabbitMQ node: Memory alarm'
  expression: last(/RabbitMQ node by HTTP/rabbitmq.node.mem_alarm)=1
  severity: average
  description: For more details see [Memory Alarms](https://www.rabbitmq.com/memory.html).
  tags:
  - tag: scope
    value: performance
- name: 'RabbitMQ node: Version has changed'
  expression: last(/RabbitMQ node by HTTP/rabbitmq.node.overview.rabbitmq_version,#1)<>last(/RabbitMQ
    node by HTTP/rabbitmq.node.overview.rabbitmq_version,#2) and length(last(/RabbitMQ
    node by HTTP/rabbitmq.node.overview.rabbitmq_version))>0
  severity: information
  description: RabbitMQ version has changed. Acknowledge to close the problem manually.
  tags:
  - tag: scope
    value: notice
- name: 'RabbitMQ node: Number of network partitions is too high'
  expression: min(/RabbitMQ node by HTTP/rabbitmq.node.partitions,5m)>0
  severity: warning
  description: For more details see [Detecting Network Partitions](https://www.rabbitmq.com/partitions.html#detecting).
  tags:
  - tag: scope
    value: performance
- name: 'RabbitMQ node: Node is not running'
  expression: max(/RabbitMQ node by HTTP/rabbitmq.node.running,5m)=0
  severity: average
  description: RabbitMQ node is not running.
  tags:
  - tag: scope
    value: availability
- name: 'RabbitMQ node: Host has been restarted'
  expression: last(/RabbitMQ node by HTTP/rabbitmq.node.uptime)<10m
  severity: information
  description: Uptime is less than 10 minutes.
  tags:
  - tag: scope
    value: notice
discovery_rules:
- name: Health Check 3.8.10+ discovery
  key: rabbitmq.healthcheck.v3810.discovery
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_node_overview
  item_prototypes:
  - name: 'Healthcheck: expiration date on the certificates{#SINGLETON}'
    key: rabbitmq.healthcheck.certificate_expiration[{#SINGLETON}]
    interval: 1m
    type: http_agent
    value_type: unsigned
  - name: 'Healthcheck: local alarms in effect on this node{#SINGLETON}'
    key: rabbitmq.healthcheck.local_alarms[{#SINGLETON}]
    interval: 1m
    type: http_agent
    value_type: unsigned
  - name: 'Healthcheck: classic mirrored queues without synchronized mirrors online{#SINGLETON}'
    key: rabbitmq.healthcheck.mirror_sync[{#SINGLETON}]
    interval: 1m
    type: http_agent
    value_type: unsigned
  - name: 'Healthcheck: queues with minimum online quorum{#SINGLETON}'
    key: rabbitmq.healthcheck.quorum[{#SINGLETON}]
    interval: 1m
    type: http_agent
    value_type: unsigned
  - name: 'Healthcheck: virtual hosts on this node{#SINGLETON}'
    key: rabbitmq.healthcheck.virtual_hosts[{#SINGLETON}]
    interval: 1m
    type: http_agent
    value_type: unsigned
  trigger_prototypes:
  - name: 'RabbitMQ node: There are valid TLS certificates expiring in the next month'
    expression: last(/RabbitMQ node by HTTP/rabbitmq.healthcheck.certificate_expiration[{#SINGLETON}])=0
    severity: average
  - name: 'RabbitMQ node: There are active alarms in the node'
    expression: last(/RabbitMQ node by HTTP/rabbitmq.healthcheck.local_alarms[{#SINGLETON}])=0
    severity: average
  - name: 'RabbitMQ node: There are queues that could potentially lose data if this
      node goes offline.'
    expression: last(/RabbitMQ node by HTTP/rabbitmq.healthcheck.mirror_sync[{#SINGLETON}])=0
    severity: average
  - name: 'RabbitMQ node: There are queues that would lose their quorum and availability
      if this node is shut down.'
    expression: last(/RabbitMQ node by HTTP/rabbitmq.healthcheck.quorum[{#SINGLETON}])=0
    severity: average
  - name: 'RabbitMQ node: There are not running virtual hosts'
    expression: last(/RabbitMQ node by HTTP/rabbitmq.healthcheck.virtual_hosts[{#SINGLETON}])=0
    severity: average
- name: Health Check 3.8.9- discovery
  key: rabbitmq.healthcheck.v389.discovery
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_node_overview
  item_prototypes:
  - name: Healthcheck{#SINGLETON}
    key: rabbitmq.healthcheck[{#SINGLETON}]
    interval: 1m
    type: http_agent
    value_type: unsigned
  trigger_prototypes:
  - name: 'RabbitMQ node: Node healthcheck failed'
    expression: last(/RabbitMQ node by HTTP/rabbitmq.healthcheck[{#SINGLETON}])=0
    severity: average
- name: Queues discovery
  key: rabbitmq.queues.discovery
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_queues
  filter:
  - macro: '{#NODE}'
    value: '{$RABBITMQ.CLUSTER.NAME}@{HOST.NAME}'
  - macro: '{#QUEUE}'
    value: '{$RABBITMQ.LLD.FILTER.QUEUE.MATCHES}'
  - macro: '{#QUEUE}'
    value: '{$RABBITMQ.LLD.FILTER.QUEUE.NOT_MATCHES}'
  item_prototypes:
  - name: 'Queue [{#VHOST}][{#QUEUE}]: Get data'
    key: rabbitmq.get_exchanges["{#VHOST}/{#QUEUE}"]
    interval: '0'
    type: dependent
    value_type: text
  - name: 'Queue [{#VHOST}][{#QUEUE}]: Consumers'
    key: rabbitmq.queue.consumers["{#VHOST}/{#QUEUE}"]
    interval: '0'
    type: dependent
    master_item_key: rabbitmq.get_exchanges["{#VHOST}/{#QUEUE}"]
    value_type: unsigned
  - name: 'Queue [{#VHOST}][{#QUEUE}]: Memory'
    key: rabbitmq.queue.memory["{#VHOST}/{#QUEUE}"]
    interval: '0'
    type: dependent
    master_item_key: rabbitmq.get_exchanges["{#VHOST}/{#QUEUE}"]
    value_type: unsigned
    units: B
  - name: 'Queue [{#VHOST}][{#QUEUE}]: Messages acknowledged per second'
    key: rabbitmq.queue.messages.ack.rate["{#VHOST}/{#QUEUE}"]
    interval: '0'
    type: dependent
    master_item_key: rabbitmq.get_exchanges["{#VHOST}/{#QUEUE}"]
  - name: 'Queue [{#VHOST}][{#QUEUE}]: Messages acknowledged'
    key: rabbitmq.queue.messages.ack["{#VHOST}/{#QUEUE}"]
    interval: '0'
    type: dependent
    master_item_key: rabbitmq.get_exchanges["{#VHOST}/{#QUEUE}"]
    value_type: unsigned
  - name: 'Queue [{#VHOST}][{#QUEUE}]: Messages delivered per second'
    key: rabbitmq.queue.messages.deliver.rate["{#VHOST}/{#QUEUE}"]
    interval: '0'
    type: dependent
    master_item_key: rabbitmq.get_exchanges["{#VHOST}/{#QUEUE}"]
  - name: 'Queue [{#VHOST}][{#QUEUE}]: Messages delivered'
    key: rabbitmq.queue.messages.deliver["{#VHOST}/{#QUEUE}"]
    interval: '0'
    type: dependent
    master_item_key: rabbitmq.get_exchanges["{#VHOST}/{#QUEUE}"]
    value_type: unsigned
  - name: 'Queue [{#VHOST}][{#QUEUE}]: Sum of messages delivered per second'
    key: rabbitmq.queue.messages.deliver_get.rate["{#VHOST}/{#QUEUE}"]
    interval: '0'
    type: dependent
    master_item_key: rabbitmq.get_exchanges["{#VHOST}/{#QUEUE}"]
  - name: 'Queue [{#VHOST}][{#QUEUE}]: Sum of messages delivered'
    key: rabbitmq.queue.messages.deliver_get["{#VHOST}/{#QUEUE}"]
    interval: '0'
    type: dependent
    master_item_key: rabbitmq.get_exchanges["{#VHOST}/{#QUEUE}"]
    value_type: unsigned
  - name: 'Queue [{#VHOST}][{#QUEUE}]: Messages published per second'
    key: rabbitmq.queue.messages.publish.rate["{#VHOST}/{#QUEUE}"]
    interval: '0'
    type: dependent
    master_item_key: rabbitmq.get_exchanges["{#VHOST}/{#QUEUE}"]
  - name: 'Queue [{#VHOST}][{#QUEUE}]: Messages published'
    key: rabbitmq.queue.messages.publish["{#VHOST}/{#QUEUE}"]
    interval: '0'
    type: dependent
    master_item_key: rabbitmq.get_exchanges["{#VHOST}/{#QUEUE}"]
    value_type: unsigned
  - name: 'Queue [{#VHOST}][{#QUEUE}]: Messages per second'
    key: rabbitmq.queue.messages.rate["{#VHOST}/{#QUEUE}"]
    interval: '0'
    type: dependent
    master_item_key: rabbitmq.get_exchanges["{#VHOST}/{#QUEUE}"]
  - name: 'Queue [{#VHOST}][{#QUEUE}]: Messages redelivered per second'
    key: rabbitmq.queue.messages.redeliver.rate["{#VHOST}/{#QUEUE}"]
    interval: '0'
    type: dependent
    master_item_key: rabbitmq.get_exchanges["{#VHOST}/{#QUEUE}"]
  - name: 'Queue [{#VHOST}][{#QUEUE}]: Messages redelivered'
    key: rabbitmq.queue.messages.redeliver["{#VHOST}/{#QUEUE}"]
    interval: '0'
    type: dependent
    master_item_key: rabbitmq.get_exchanges["{#VHOST}/{#QUEUE}"]
    value_type: unsigned
  - name: 'Queue [{#VHOST}][{#QUEUE}]: Messages total'
    key: rabbitmq.queue.messages["{#VHOST}/{#QUEUE}"]
    interval: '0'
    type: dependent
    master_item_key: rabbitmq.get_exchanges["{#VHOST}/{#QUEUE}"]
    value_type: unsigned
  - name: 'Queue [{#VHOST}][{#QUEUE}]: Messages ready per second'
    key: rabbitmq.queue.messages_ready.rate["{#VHOST}/{#QUEUE}"]
    interval: '0'
    type: dependent
    master_item_key: rabbitmq.get_exchanges["{#VHOST}/{#QUEUE}"]
  - name: 'Queue [{#VHOST}][{#QUEUE}]: Messages ready'
    key: rabbitmq.queue.messages_ready["{#VHOST}/{#QUEUE}"]
    interval: '0'
    type: dependent
    master_item_key: rabbitmq.get_exchanges["{#VHOST}/{#QUEUE}"]
    value_type: unsigned
  - name: 'Queue [{#VHOST}][{#QUEUE}]: Messages unacknowledged per second'
    key: rabbitmq.queue.messages_unacknowledged.rate["{#VHOST}/{#QUEUE}"]
    interval: '0'
    type: dependent
    master_item_key: rabbitmq.get_exchanges["{#VHOST}/{#QUEUE}"]
  - name: 'Queue [{#VHOST}][{#QUEUE}]: Messages unacknowledged'
    key: rabbitmq.queue.messages_unacknowledged["{#VHOST}/{#QUEUE}"]
    interval: '0'
    type: dependent
    master_item_key: rabbitmq.get_exchanges["{#VHOST}/{#QUEUE}"]
    value_type: unsigned
  trigger_prototypes:
  - name: 'RabbitMQ node: Too many messages in queue [{#VHOST}][{#QUEUE}]'
    expression: min(/RabbitMQ node by HTTP/rabbitmq.queue.messages["{#VHOST}/{#QUEUE}"],5m)>1000
    severity: warning
