template: RabbitMQ cluster by HTTP
description: "This template is developed to monitor the messaging broker RabbitMQ\
  \ cluster by Zabbix that works without any external scripts.\r\nMost of the metrics\
  \ are collected in one go, thanks to Zabbix bulk data collection.\r\n\r\nThe template\
  \ collects metrics by polling RabbitMQ management plugin with HTTP agent remotely.\r\
  \n\r\nSetup:\r\n\r\n1. Enable the RabbitMQ management plugin. See the RabbitMQ documentation\
  \ for the instructions:\r\nhttps://www.rabbitmq.com/management.html\r\n\r\n2. Create\
  \ a user to monitor the service:\r\n\r\nrabbitmqctl add_user zbx_monitor <PASSWORD>\r\
  \nrabbitmqctl set_permissions  -p / zbx_monitor \"\" \"\" \".*\"\r\nrabbitmqctl\
  \ set_user_tags zbx_monitor monitoring\r\n\r\n3. Set the hostname or IP address\
  \ of the RabbitMQ cluster host in the '{$RABBITMQ.API.CLUSTER_HOST}' macro. You\
  \ can also change the port in the '{$RABBITMQ.API.PORT}' macro and the scheme in\
  \ the '{$RABBITMQ.API.SCHEME}' macro if necessary.\r\n\r\n4. Set the user name and\
  \ password in the macros '{$RABBITMQ.API.USER}' and '{$RABBITMQ.API.PASSWORD}'.\r\
  \n\r\nYou can discuss this template or leave feedback on our forum https://www.zabbix.com/forum/zabbix-suggestions-and-feedback/387226-discussion-thread-for-official-zabbix-template-rabbitmq\r\
  \n\r\nGenerated by official Zabbix template tool \"Templator\""
groups:
- Templates
items:
- name: Get exchanges
  key: rabbitmq.get_exchanges
  interval: 1m
  type: http_agent
  value_type: text
  description: The HTTP API endpoint that returns exchanges metrics.
  history: 1h
  trends: '0'
  tags:
  - tag: component
    value: raw
- name: Get overview
  key: rabbitmq.get_overview
  interval: 1m
  type: http_agent
  value_type: text
  description: The HTTP API endpoint that returns cluster-wide metrics.
  history: 1h
  trends: '0'
  tags:
  - tag: component
    value: raw
- name: Messages acknowledged
  key: rabbitmq.overview.messages.ack
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_overview
  value_type: unsigned
  description: The number of messages delivered to clients and acknowledged.
  history: 31d
  tags:
  - tag: component
    value: messages
- name: Messages acknowledged per second
  key: rabbitmq.overview.messages.ack.rate
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_overview
  description: The rate of messages (per second) delivered to clients and acknowledged.
  history: 31d
  tags:
  - tag: component
    value: messages
- name: Messages confirmed
  key: rabbitmq.overview.messages.confirm
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_overview
  value_type: unsigned
  description: The count of confirmed messages.
  history: 31d
  tags:
  - tag: component
    value: messages
- name: Messages confirmed per second
  key: rabbitmq.overview.messages.confirm.rate
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_overview
  description: The rate of messages confirmed per second.
  history: 31d
  tags:
  - tag: component
    value: messages
- name: Messages delivered
  key: rabbitmq.overview.messages.deliver_get
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_overview
  value_type: unsigned
  description: 'The sum of messages delivered to consumers: in acknowledgement mode
    and in no-acknowledgement mode; delivered to consumers in response to the `basic.get`:
    in acknowledgement mode and in no-acknowledgement mode.'
  history: 31d
  tags:
  - tag: component
    value: messages
- name: Messages delivered per second
  key: rabbitmq.overview.messages.deliver_get.rate
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_overview
  description: 'The rate of the sum of messages (per second) delivered to consumers:
    in acknowledgement mode and in no-acknowledgement mode; delivered to consumers
    in response to the `basic.get`: in acknowledgement mode and in no-acknowledgement
    mode.'
  history: 31d
  tags:
  - tag: component
    value: messages
- name: Messages published
  key: rabbitmq.overview.messages.publish
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_overview
  value_type: unsigned
  description: The count of published messages.
  history: 31d
  tags:
  - tag: component
    value: messages
- name: Messages published per second
  key: rabbitmq.overview.messages.publish.rate
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_overview
  description: The rate of messages published per second.
  history: 31d
  tags:
  - tag: component
    value: messages
- name: Messages publish_in
  key: rabbitmq.overview.messages.publish_in
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_overview
  value_type: unsigned
  description: The count of messages published from the channels into this overview.
  history: 31d
  tags:
  - tag: component
    value: messages
- name: Messages publish_in per second
  key: rabbitmq.overview.messages.publish_in.rate
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_overview
  description: The rate of messages (per second) published from the channels into
    this overview.
  history: 31d
  tags:
  - tag: component
    value: messages
- name: Messages publish_out
  key: rabbitmq.overview.messages.publish_out
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_overview
  value_type: unsigned
  description: The count of messages published from this overview into queues.
  history: 31d
  tags:
  - tag: component
    value: messages
- name: Messages publish_out per second
  key: rabbitmq.overview.messages.publish_out.rate
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_overview
  description: The rate of messages (per second) published from this overview into
    queues.
  history: 31d
  tags:
  - tag: component
    value: messages
- name: Messages returned redeliver
  key: rabbitmq.overview.messages.redeliver
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_overview
  value_type: unsigned
  description: The count of subset of messages in the `deliver_get`, which had the
    `redelivered` flag set.
  history: 31d
  tags:
  - tag: component
    value: messages
- name: Messages returned redeliver per second
  key: rabbitmq.overview.messages.redeliver.rate
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_overview
  description: The rate of subset of messages (per second) in the `deliver_get`, which
    had the `redelivered` flag set.
  history: 31d
  tags:
  - tag: component
    value: messages
- name: Messages returned unroutable
  key: rabbitmq.overview.messages.return_unroutable
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_overview
  value_type: unsigned
  description: The count of messages returned to a publisher as unroutable.
  history: 31d
  tags:
  - tag: component
    value: messages
- name: Messages returned unroutable per second
  key: rabbitmq.overview.messages.return_unroutable.rate
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_overview
  description: The rate of messages (per second) returned to a publisher as unroutable.
  history: 31d
  tags:
  - tag: component
    value: messages
- name: Channels total
  key: rabbitmq.overview.object_totals.channels
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_overview
  value_type: unsigned
  description: The total number of channels.
  history: 31d
  tags:
  - tag: component
    value: channels
- name: Connections total
  key: rabbitmq.overview.object_totals.connections
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_overview
  value_type: unsigned
  description: The total number of connections.
  history: 31d
  tags:
  - tag: component
    value: connections
- name: Consumers total
  key: rabbitmq.overview.object_totals.consumers
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_overview
  value_type: unsigned
  description: The total number of consumers.
  history: 31d
  tags:
  - tag: component
    value: consumers
- name: Exchanges total
  key: rabbitmq.overview.object_totals.exchanges
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_overview
  value_type: unsigned
  description: The total number of exchanges.
  history: 31d
  tags:
  - tag: component
    value: exchanges
- name: Queues total
  key: rabbitmq.overview.object_totals.queues
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_overview
  value_type: unsigned
  description: The total number of queues.
  history: 31d
  tags:
  - tag: component
    value: queues
- name: Messages total
  key: rabbitmq.overview.queue_totals.messages
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_overview
  value_type: unsigned
  description: The total number of messages (ready, plus unacknowledged).
  history: 31d
  tags:
  - tag: component
    value: messages
- name: Messages ready for delivery
  key: rabbitmq.overview.queue_totals.messages.ready
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_overview
  value_type: unsigned
  description: The number of messages ready for delivery.
  history: 31d
  tags:
  - tag: component
    value: messages
- name: Messages unacknowledged
  key: rabbitmq.overview.queue_totals.messages.unacknowledged
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_overview
  value_type: unsigned
  description: The number of unacknowledged messages.
  history: 31d
  tags:
  - tag: component
    value: messages
triggers:
- name: 'RabbitMQ cluster: Failed to fetch overview data'
  expression: nodata(/RabbitMQ cluster by HTTP/rabbitmq.get_overview,30m)=1
  severity: warning
  description: Zabbix has not received any data for items for the last 30 minutes.
  tags:
  - tag: scope
    value: availability
discovery_rules:
- name: Exchanges discovery
  key: rabbitmq.exchanges.discovery
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_exchanges
  filter:
  - macro: '{#EXCHANGE}'
    value: '{$RABBITMQ.LLD.FILTER.EXCHANGE.MATCHES}'
  - macro: '{#EXCHANGE}'
    value: '{$RABBITMQ.LLD.FILTER.EXCHANGE.NOT_MATCHES}'
  item_prototypes:
  - name: 'Exchange [{#VHOST}][{#EXCHANGE}][{#TYPE}]: Get data'
    key: rabbitmq.get_exchanges["{#VHOST}/{#EXCHANGE}/{#TYPE}"]
    interval: '0'
    type: dependent
    value_type: text
  - name: 'Exchange [{#VHOST}][{#EXCHANGE}][{#TYPE}]: Messages acknowledged per second'
    key: rabbitmq.exchange.messages.ack.rate["{#VHOST}/{#EXCHANGE}/{#TYPE}"]
    interval: '0'
    type: dependent
    master_item_key: rabbitmq.get_exchanges["{#VHOST}/{#EXCHANGE}/{#TYPE}"]
  - name: 'Exchange [{#VHOST}][{#EXCHANGE}][{#TYPE}]: Messages acknowledged'
    key: rabbitmq.exchange.messages.ack["{#VHOST}/{#EXCHANGE}/{#TYPE}"]
    interval: '0'
    type: dependent
    master_item_key: rabbitmq.get_exchanges["{#VHOST}/{#EXCHANGE}/{#TYPE}"]
    value_type: unsigned
  - name: 'Exchange [{#VHOST}][{#EXCHANGE}][{#TYPE}]: Messages confirmed per second'
    key: rabbitmq.exchange.messages.confirm.rate["{#VHOST}/{#EXCHANGE}/{#TYPE}"]
    interval: '0'
    type: dependent
    master_item_key: rabbitmq.get_exchanges["{#VHOST}/{#EXCHANGE}/{#TYPE}"]
  - name: 'Exchange [{#VHOST}][{#EXCHANGE}][{#TYPE}]: Messages confirmed'
    key: rabbitmq.exchange.messages.confirm["{#VHOST}/{#EXCHANGE}/{#TYPE}"]
    interval: '0'
    type: dependent
    master_item_key: rabbitmq.get_exchanges["{#VHOST}/{#EXCHANGE}/{#TYPE}"]
    value_type: unsigned
  - name: 'Exchange [{#VHOST}][{#EXCHANGE}][{#TYPE}]: Messages delivered per second'
    key: rabbitmq.exchange.messages.deliver_get.rate["{#VHOST}/{#EXCHANGE}/{#TYPE}"]
    interval: '0'
    type: dependent
    master_item_key: rabbitmq.get_exchanges["{#VHOST}/{#EXCHANGE}/{#TYPE}"]
  - name: 'Exchange [{#VHOST}][{#EXCHANGE}][{#TYPE}]: Messages delivered'
    key: rabbitmq.exchange.messages.deliver_get["{#VHOST}/{#EXCHANGE}/{#TYPE}"]
    interval: '0'
    type: dependent
    master_item_key: rabbitmq.get_exchanges["{#VHOST}/{#EXCHANGE}/{#TYPE}"]
    value_type: unsigned
  - name: 'Exchange [{#VHOST}][{#EXCHANGE}][{#TYPE}]: Messages published per second'
    key: rabbitmq.exchange.messages.publish.rate["{#VHOST}/{#EXCHANGE}/{#TYPE}"]
    interval: '0'
    type: dependent
    master_item_key: rabbitmq.get_exchanges["{#VHOST}/{#EXCHANGE}/{#TYPE}"]
  - name: 'Exchange [{#VHOST}][{#EXCHANGE}][{#TYPE}]: Messages published'
    key: rabbitmq.exchange.messages.publish["{#VHOST}/{#EXCHANGE}/{#TYPE}"]
    interval: '0'
    type: dependent
    master_item_key: rabbitmq.get_exchanges["{#VHOST}/{#EXCHANGE}/{#TYPE}"]
    value_type: unsigned
  - name: 'Exchange [{#VHOST}][{#EXCHANGE}][{#TYPE}]: Messages publish_in per second'
    key: rabbitmq.exchange.messages.publish_in.rate["{#VHOST}/{#EXCHANGE}/{#TYPE}"]
    interval: '0'
    type: dependent
    master_item_key: rabbitmq.get_exchanges["{#VHOST}/{#EXCHANGE}/{#TYPE}"]
  - name: 'Exchange [{#VHOST}][{#EXCHANGE}][{#TYPE}]: Messages publish_in'
    key: rabbitmq.exchange.messages.publish_in["{#VHOST}/{#EXCHANGE}/{#TYPE}"]
    interval: '0'
    type: dependent
    master_item_key: rabbitmq.get_exchanges["{#VHOST}/{#EXCHANGE}/{#TYPE}"]
    value_type: unsigned
  - name: 'Exchange [{#VHOST}][{#EXCHANGE}][{#TYPE}]: Messages publish_out per second'
    key: rabbitmq.exchange.messages.publish_out.rate["{#VHOST}/{#EXCHANGE}/{#TYPE}"]
    interval: '0'
    type: dependent
    master_item_key: rabbitmq.get_exchanges["{#VHOST}/{#EXCHANGE}/{#TYPE}"]
  - name: 'Exchange [{#VHOST}][{#EXCHANGE}][{#TYPE}]: Messages publish_out'
    key: rabbitmq.exchange.messages.publish_out["{#VHOST}/{#EXCHANGE}/{#TYPE}"]
    interval: '0'
    type: dependent
    master_item_key: rabbitmq.get_exchanges["{#VHOST}/{#EXCHANGE}/{#TYPE}"]
    value_type: unsigned
  - name: 'Exchange {#VHOST}/{#EXCHANGE}/{#TYPE}: Messages redelivered per second'
    key: rabbitmq.exchange.messages.redeliver.rate["{#VHOST}/{#EXCHANGE}/{#TYPE}"]
    interval: '0'
    type: dependent
    master_item_key: rabbitmq.get_exchanges["{#VHOST}/{#EXCHANGE}/{#TYPE}"]
  - name: 'Exchange [{#VHOST}][{#EXCHANGE}][{#TYPE}]: Messages redelivered'
    key: rabbitmq.exchange.messages.redeliver["{#VHOST}/{#EXCHANGE}/{#TYPE}"]
    interval: '0'
    type: dependent
    master_item_key: rabbitmq.get_exchanges["{#VHOST}/{#EXCHANGE}/{#TYPE}"]
    value_type: unsigned
  - name: 'Exchange [{#VHOST}][{#EXCHANGE}][{#TYPE}]: Messages returned unroutable
      per second'
    key: rabbitmq.exchange.messages.return_unroutable.rate["{#VHOST}/{#EXCHANGE}/{#TYPE}"]
    interval: '0'
    type: dependent
    master_item_key: rabbitmq.get_exchanges["{#VHOST}/{#EXCHANGE}/{#TYPE}"]
  - name: 'Exchange [{#VHOST}][{#EXCHANGE}][{#TYPE}]: Messages returned unroutable'
    key: rabbitmq.exchange.messages.return_unroutable["{#VHOST}/{#EXCHANGE}/{#TYPE}"]
    interval: '0'
    type: dependent
    master_item_key: rabbitmq.get_exchanges["{#VHOST}/{#EXCHANGE}/{#TYPE}"]
    value_type: unsigned
- name: Health Check 3.8.10+ discovery
  key: rabbitmq.healthcheck.v3810.discovery
  interval: '0'
  type: dependent
  master_item_key: rabbitmq.get_overview
  item_prototypes:
  - name: 'Healthcheck: alarms in effect in the cluster{#SINGLETON}'
    key: rabbitmq.healthcheck.alarms[{#SINGLETON}]
    interval: 1m
    type: http_agent
    value_type: unsigned
  trigger_prototypes:
  - name: 'RabbitMQ cluster: There are active alarms in the cluster'
    expression: last(/RabbitMQ cluster by HTTP/rabbitmq.healthcheck.alarms[{#SINGLETON}])=0
    severity: average
