template: Ubiquiti AirOS by SNMP
description: "Template Net Ubiquiti AirOS\r\n\r\nMIBs used:\r\nFROGFOOT-RESOURCES-MIB\r\
  \nHOST-RESOURCES-MIB\r\nSNMPv2-MIB\r\nIEEE802dot11-MIB\r\nIF-MIB\r\n\r\nKnown Issues:\r\
  \n\r\n  Description: UBNT unifi reports speed: like IF-MIB::ifSpeed.1 = Gauge32:\
  \ 4294967295 for all interfaces\r\n  Version: Firmware: BZ.ar7240.v3.7.51.6230.170322.1513\r\
  \n  Device: UBNT UAP-LR\r\n\r\n  Description: UBNT AirMax(NanoStation, NanoBridge\
  \ etc) reports ifSpeed: as 0 for VLAN and wireless(ath0) interfaces\r\n  Version:\
  \ Firmware: XW.ar934x.v5.6-beta4.22359.140521.1836\r\n  Device: NanoStation M5\r\
  \n\r\n  Description: UBNT AirMax(NanoStation, NanoBridge etc) reports always return\
  \ ifType: as ethernet(6) even for wifi,vlans and other types\r\n  Version: Firmware:\
  \ XW.ar934x.v5.6-beta4.22359.140521.1836\r\n  Device: NanoStation M5\r\n\r\n  Description:\
  \ ifXTable is not provided in IF-MIB. So Interfaces Simple Template is used instead\r\
  \n  Version: all above\r\n  Device: NanoStation, UAP-LR\r\n\r\nGenerated by official\
  \ Zabbix template tool \"Templator\""
groups:
- Templates
items:
- name: ICMP ping
  key: icmpping
  interval: 1m
  type: simple_check
  value_type: unsigned
  description: "The host accessibility by ICMP ping.\r\n\r\n0 - ICMP ping fails;\r\
    \n1 - ICMP ping successful."
  history: 31d
  tags:
  - tag: component
    value: health
  - tag: component
    value: network
- name: ICMP loss
  key: icmppingloss
  interval: 1m
  type: simple_check
  units: '%'
  description: The percentage of lost packets.
  history: 31d
  tags:
  - tag: component
    value: health
  - tag: component
    value: network
- name: ICMP response time
  key: icmppingsec
  interval: 1m
  type: simple_check
  units: s
  description: The ICMP ping response time (in seconds).
  history: 31d
  tags:
  - tag: component
    value: health
  - tag: component
    value: network
- name: SNMP traps (fallback)
  key: snmptrap.fallback
  interval: '0'
  type: snmp_trap
  value_type: log
  description: The item is used to collect all SNMP traps unmatched by other snmptrap
    items
  history: 31d
  trends: '0'
  tags:
  - tag: component
    value: network
- name: System contact details
  key: system.contact[sysContact.0]
  interval: 15m
  value_type: char
  description: "MIB: SNMPv2-MIB\r\nThe textual identification of the contact person\
    \ for this managed node, together with information on how to contact this person.\
    \ If no contact information is known, the value is the zero-length string."
  history: 31d
  trends: '0'
  tags:
  - tag: component
    value: system
- name: Load average (15m avg)
  key: system.cpu.load.avg15[loadValue.3]
  interval: 1m
  description: "MIB: FROGFOOT-RESOURCES-MIB\r\n15 minute load average of processor\
    \ load."
  history: 31d
  tags:
  - tag: component
    value: cpu
- name: Load average (1m avg)
  key: system.cpu.load.avg1[loadValue.1]
  interval: 1m
  description: "MIB: FROGFOOT-RESOURCES-MIB\r\n1 minute load average of processor\
    \ load."
  history: 31d
  tags:
  - tag: component
    value: cpu
- name: Load average (5m avg)
  key: system.cpu.load.avg5[loadValue.2]
  interval: 1m
  description: "MIB: FROGFOOT-RESOURCES-MIB\r\n5 minute load average of processor\
    \ load."
  history: 31d
  tags:
  - tag: component
    value: cpu
- name: System description
  key: system.descr[sysDescr.0]
  interval: 15m
  value_type: char
  description: "MIB: SNMPv2-MIB\r\nA textual description of the entity. This value\
    \ should\r\ninclude the full name and version identification of the system's hardware\
    \ type, software operating-system, and\r\nnetworking software."
  history: 31d
  trends: '0'
  tags:
  - tag: component
    value: system
- name: Firmware version
  key: system.hw.firmware
  interval: 1h
  value_type: char
  description: "MIB: IEEE802dot11-MIB\r\nPrintable string used to identify the manufacturer's\
    \ product version of the resource. Maximum string length is 128 octets."
  history: 31d
  trends: '0'
  tags:
  - tag: component
    value: system
- name: Hardware model name
  key: system.hw.model
  interval: 1h
  value_type: char
  description: "MIB: IEEE802dot11-MIB\r\nA printable string used to identify the manufacturer's\
    \ product name of the resource. Maximum string length is 128 octets."
  history: 31d
  trends: '0'
  tags:
  - tag: component
    value: system
- name: Uptime (hardware)
  key: system.hw.uptime[hrSystemUptime.0]
  interval: 30s
  value_type: unsigned
  units: uptime
  description: "MIB: HOST-RESOURCES-MIB\r\nThe amount of time since this host was\
    \ last initialized. Note that this is different from sysUpTime in the SNMPv2-MIB\
    \ [RFC1907] because sysUpTime is the uptime of the network management portion\
    \ of the system."
  history: 31d
  trends: '0'
  tags:
  - tag: component
    value: system
- name: System location
  key: system.location[sysLocation.0]
  interval: 15m
  value_type: char
  description: "MIB: SNMPv2-MIB\r\nPhysical location of the node (e.g., `equipment\
    \ room`, `3rd floor`). If not provided, the value is a zero-length string."
  history: 31d
  trends: '0'
  tags:
  - tag: component
    value: system
- name: System name
  key: system.name
  interval: 15m
  value_type: char
  description: "MIB: SNMPv2-MIB\r\nAn administratively-assigned name for this managed\
    \ node.By convention, this is the node's fully-qualified domain name. If the name\
    \ is unknown, the value is the zero-length string."
  history: 31d
  trends: '0'
  tags:
  - tag: component
    value: system
- name: Uptime (network)
  key: system.net.uptime[sysUpTime.0]
  interval: 30s
  value_type: unsigned
  units: uptime
  description: "MIB: SNMPv2-MIB\r\nTime (in hundredths of a second) since the network\
    \ management portion of the system was last re-initialized."
  history: 31d
  trends: '0'
  tags:
  - tag: component
    value: system
- name: System object ID
  key: system.objectid[sysObjectID.0]
  interval: 15m
  value_type: char
  description: "MIB: SNMPv2-MIB\r\nThe vendor's authoritative identification of the\
    \ network management subsystem contained in the entity. This value is allocated\
    \ within the SMI enterprises subtree (1.3.6.1.4.1) and provides an easy and unambiguous\
    \ means for determining`what kind of box' is being managed.  For example, if vendor`Flintstones,\
    \ Inc.' was assigned the subtree1.3.6.1.4.1.4242, it could assign the identifier\
    \ 1.3.6.1.4.1.4242.1.1 to its `Fred Router'."
  history: 31d
  trends: '0'
  tags:
  - tag: component
    value: system
- name: Memory (buffers)
  key: vm.memory.buffers[memBuffer.0]
  interval: 1m
  value_type: unsigned
  units: B
  description: "MIB: FROGFOOT-RESOURCES-MIB\r\nMemory used by kernel buffers (Buffers\
    \ in /proc/meminfo)."
  history: 31d
  tags:
  - tag: component
    value: memory
- name: Memory (cached)
  key: vm.memory.cached[memCache.0]
  interval: 1m
  value_type: unsigned
  units: B
  description: "MIB: FROGFOOT-RESOURCES-MIB\r\nMemory used by the page cache and slabs\
    \ (Cached and Slab in /proc/meminfo)."
  history: 31d
  tags:
  - tag: component
    value: memory
- name: Free memory
  key: vm.memory.free[memFree.0]
  interval: 1m
  value_type: unsigned
  units: B
  description: 'MIB: FROGFOOT-RESOURCES-MIB'
  history: 31d
  tags:
  - tag: component
    value: memory
- name: Total memory
  key: vm.memory.total[memTotal.0]
  interval: 1m
  value_type: unsigned
  units: B
  description: "MIB: FROGFOOT-RESOURCES-MIB\r\nThe total memory expressed in bytes."
  history: 31d
  tags:
  - tag: component
    value: memory
- name: Memory utilization
  key: vm.memory.util[memoryUsedPercentage]
  interval: 1m
  type: calculated
  params: (last(//vm.memory.total[memTotal.0])-(last(//vm.memory.free[memFree.0])+last(//vm.memory.buffers[memBuffer.0])+last(//vm.memory.cached[memCache.0])))/last(//vm.memory.total[memTotal.0])*100
  units: '%'
  description: Memory utilization in %.
  history: 31d
  tags:
  - tag: component
    value: memory
- name: SNMP agent availability
  key: zabbix[host,snmp,available]
  interval: 1m
  type: zabbix_internal
  value_type: unsigned
  description: "Availability of SNMP checks on the host. The value of this item corresponds\
    \ to availability icons in the host list.\r\nPossible values:\r\n0 - not available\r\
    \n1 - available\r\n2 - unknown"
  history: 31d
  tags:
  - tag: component
    value: health
  - tag: component
    value: network
triggers:
- name: 'Ubiquiti AirOS: Unavailable by ICMP ping'
  expression: max(/Ubiquiti AirOS by SNMP/icmpping,#3)=0
  severity: high
  description: Last three attempts returned timeout. Please check device connectivity.
  tags:
  - tag: scope
    value: availability
- name: 'Ubiquiti AirOS: High ICMP ping loss'
  expression: min(/Ubiquiti AirOS by SNMP/icmppingloss,5m)>20 and min(/Ubiquiti AirOS
    by SNMP/icmppingloss,5m)<100
  severity: warning
  description: ICMP packets loss detected.
  tags:
  - tag: scope
    value: availability
  - tag: scope
    value: performance
- name: 'Ubiquiti AirOS: High ICMP ping response time'
  expression: avg(/Ubiquiti AirOS by SNMP/icmppingsec,5m)>0.15
  severity: warning
  description: Average ICMP response time is too high.
  tags:
  - tag: scope
    value: availability
  - tag: scope
    value: performance
- name: 'Ubiquiti AirOS: Firmware has changed'
  expression: last(/Ubiquiti AirOS by SNMP/system.hw.firmware,#1)<>last(/Ubiquiti
    AirOS by SNMP/system.hw.firmware,#2) and length(last(/Ubiquiti AirOS by SNMP/system.hw.firmware))>0
  severity: information
  description: Firmware version has changed. Acknowledge to close the problem manually.
  tags:
  - tag: scope
    value: notice
- name: 'Ubiquiti AirOS: Host has been restarted'
  expression: (last(/Ubiquiti AirOS by SNMP/system.hw.uptime[hrSystemUptime.0])>0
    and last(/Ubiquiti AirOS by SNMP/system.hw.uptime[hrSystemUptime.0])<10m) or (last(/Ubiquiti
    AirOS by SNMP/system.hw.uptime[hrSystemUptime.0])=0 and last(/Ubiquiti AirOS by
    SNMP/system.net.uptime[sysUpTime.0])<10m)
  severity: warning
  description: Uptime is less than 10 minutes.
  tags:
  - tag: scope
    value: notice
- name: 'Ubiquiti AirOS: System name has changed'
  expression: last(/Ubiquiti AirOS by SNMP/system.name,#1)<>last(/Ubiquiti AirOS by
    SNMP/system.name,#2) and length(last(/Ubiquiti AirOS by SNMP/system.name))>0
  severity: information
  description: The name of the system has changed. Acknowledge to close the problem
    manually.
  tags:
  - tag: scope
    value: notice
  - tag: scope
    value: security
- name: 'Ubiquiti AirOS: High memory utilization'
  expression: min(/Ubiquiti AirOS by SNMP/vm.memory.util[memoryUsedPercentage],5m)>90
  severity: average
  description: The system is running out of free memory.
  tags:
  - tag: scope
    value: capacity
  - tag: scope
    value: performance
- name: 'Ubiquiti AirOS: No SNMP data collection'
  expression: max(/Ubiquiti AirOS by SNMP/zabbix[host,snmp,available],5m)=0
  severity: warning
  description: SNMP is not available for polling. Please check device connectivity
    and SNMP settings.
  tags:
  - tag: scope
    value: availability
discovery_rules:
- name: Network interfaces discovery
  key: net.if.discovery
  interval: 1h
  filter:
  - macro: '{#IFADMINSTATUS}'
    value: '{$NET.IF.IFADMINSTATUS.MATCHES}'
  - macro: '{#IFADMINSTATUS}'
    value: '{$NET.IF.IFADMINSTATUS.NOT_MATCHES}'
  - macro: '{#IFALIAS}'
    value: '{$NET.IF.IFALIAS.MATCHES}'
  - macro: '{#IFALIAS}'
    value: '{$NET.IF.IFALIAS.NOT_MATCHES}'
  - macro: '{#IFDESCR}'
    value: '{$NET.IF.IFDESCR.MATCHES}'
  - macro: '{#IFDESCR}'
    value: '{$NET.IF.IFDESCR.NOT_MATCHES}'
  - macro: '{#IFNAME}'
    value: '{$NET.IF.IFNAME.MATCHES}'
  - macro: '{#IFNAME}'
    value: '{$NET.IF.IFNAME.NOT_MATCHES}'
  - macro: '{#IFOPERSTATUS}'
    value: '{$NET.IF.IFOPERSTATUS.MATCHES}'
  - macro: '{#IFOPERSTATUS}'
    value: '{$NET.IF.IFOPERSTATUS.NOT_MATCHES}'
  - macro: '{#IFTYPE}'
    value: '{$NET.IF.IFTYPE.MATCHES}'
  - macro: '{#IFTYPE}'
    value: '{$NET.IF.IFTYPE.NOT_MATCHES}'
  item_prototypes:
  - name: 'Interface {#IFNAME}({#IFALIAS}): Inbound packets discarded'
    key: net.if.in.discards[ifInDiscards.{#SNMPINDEX}]
    interval: 3m
    value_type: unsigned
  - name: 'Interface {#IFNAME}({#IFALIAS}): Inbound packets with errors'
    key: net.if.in.errors[ifInErrors.{#SNMPINDEX}]
    interval: 3m
    value_type: unsigned
  - name: 'Interface {#IFNAME}({#IFALIAS}): Bits received'
    key: net.if.in[ifInOctets.{#SNMPINDEX}]
    interval: 3m
    value_type: unsigned
    units: bps
  - name: 'Interface {#IFNAME}({#IFALIAS}): Outbound packets discarded'
    key: net.if.out.discards[ifOutDiscards.{#SNMPINDEX}]
    interval: 3m
    value_type: unsigned
  - name: 'Interface {#IFNAME}({#IFALIAS}): Outbound packets with errors'
    key: net.if.out.errors[ifOutErrors.{#SNMPINDEX}]
    interval: 3m
    value_type: unsigned
  - name: 'Interface {#IFNAME}({#IFALIAS}): Bits sent'
    key: net.if.out[ifOutOctets.{#SNMPINDEX}]
    interval: 3m
    value_type: unsigned
    units: bps
  - name: 'Interface {#IFNAME}({#IFALIAS}): Speed'
    key: net.if.speed[ifSpeed.{#SNMPINDEX}]
    interval: 5m
    value_type: unsigned
    units: bps
  - name: 'Interface {#IFNAME}({#IFALIAS}): Operational status'
    key: net.if.status[ifOperStatus.{#SNMPINDEX}]
    interval: 1m
    value_type: unsigned
  - name: 'Interface {#IFNAME}({#IFALIAS}): Interface type'
    key: net.if.type[ifType.{#SNMPINDEX}]
    interval: 1h
    value_type: unsigned
  trigger_prototypes:
  - name: 'Ubiquiti AirOS: Interface {#IFNAME}({#IFALIAS}): High error rate'
    expression: "min(/Ubiquiti AirOS by SNMP/net.if.in.errors[ifInErrors.{#SNMPINDEX}],5m)>2\r\
      \nor min(/Ubiquiti AirOS by SNMP/net.if.out.errors[ifOutErrors.{#SNMPINDEX}],5m)>2"
    severity: warning
    recovery_expression: "max(/Ubiquiti AirOS by SNMP/net.if.in.errors[ifInErrors.{#SNMPINDEX}],5m)<2*0.8\r\
      \nand max(/Ubiquiti AirOS by SNMP/net.if.out.errors[ifOutErrors.{#SNMPINDEX}],5m)<2*0.8"
    allow_manual_close: true
  - name: 'Ubiquiti AirOS: Interface {#IFNAME}({#IFALIAS}): High bandwidth usage'
    expression: "(avg(/Ubiquiti AirOS by SNMP/net.if.in[ifInOctets.{#SNMPINDEX}],15m)>(95/100)*last(/Ubiquiti\
      \ AirOS by SNMP/net.if.speed[ifSpeed.{#SNMPINDEX}]) or\r\navg(/Ubiquiti AirOS\
      \ by SNMP/net.if.out[ifOutOctets.{#SNMPINDEX}],15m)>(95/100)*last(/Ubiquiti\
      \ AirOS by SNMP/net.if.speed[ifSpeed.{#SNMPINDEX}])) and\r\nlast(/Ubiquiti AirOS\
      \ by SNMP/net.if.speed[ifSpeed.{#SNMPINDEX}])>0"
    severity: warning
    recovery_expression: "avg(/Ubiquiti AirOS by SNMP/net.if.in[ifInOctets.{#SNMPINDEX}],15m)<((95-3)/100)*last(/Ubiquiti\
      \ AirOS by SNMP/net.if.speed[ifSpeed.{#SNMPINDEX}]) and\r\navg(/Ubiquiti AirOS\
      \ by SNMP/net.if.out[ifOutOctets.{#SNMPINDEX}],15m)<((95-3)/100)*last(/Ubiquiti\
      \ AirOS by SNMP/net.if.speed[ifSpeed.{#SNMPINDEX}])"
    allow_manual_close: true
  - name: 'Ubiquiti AirOS: Interface {#IFNAME}({#IFALIAS}): Ethernet has changed to
      lower speed than it was before'
    expression: "change(/Ubiquiti AirOS by SNMP/net.if.speed[ifSpeed.{#SNMPINDEX}])<0\
      \ and last(/Ubiquiti AirOS by SNMP/net.if.speed[ifSpeed.{#SNMPINDEX}])>0\r\n\
      and (\r\nlast(/Ubiquiti AirOS by SNMP/net.if.type[ifType.{#SNMPINDEX}])=6 or\r\
      \nlast(/Ubiquiti AirOS by SNMP/net.if.type[ifType.{#SNMPINDEX}])=7 or\r\nlast(/Ubiquiti\
      \ AirOS by SNMP/net.if.type[ifType.{#SNMPINDEX}])=11 or\r\nlast(/Ubiquiti AirOS\
      \ by SNMP/net.if.type[ifType.{#SNMPINDEX}])=62 or\r\nlast(/Ubiquiti AirOS by\
      \ SNMP/net.if.type[ifType.{#SNMPINDEX}])=69 or\r\nlast(/Ubiquiti AirOS by SNMP/net.if.type[ifType.{#SNMPINDEX}])=117\r\
      \n)\r\nand\r\n(last(/Ubiquiti AirOS by SNMP/net.if.status[ifOperStatus.{#SNMPINDEX}])<>2)"
    severity: information
    recovery_expression: "(change(/Ubiquiti AirOS by SNMP/net.if.speed[ifSpeed.{#SNMPINDEX}])>0\
      \ and last(/Ubiquiti AirOS by SNMP/net.if.speed[ifSpeed.{#SNMPINDEX}],#2)>0)\
      \ or\r\n(last(/Ubiquiti AirOS by SNMP/net.if.status[ifOperStatus.{#SNMPINDEX}])=2)"
    allow_manual_close: true
  - name: 'Ubiquiti AirOS: Interface {#IFNAME}({#IFALIAS}): Link down'
    expression: 1=1 and last(/Ubiquiti AirOS by SNMP/net.if.status[ifOperStatus.{#SNMPINDEX}])=2
      and (last(/Ubiquiti AirOS by SNMP/net.if.status[ifOperStatus.{#SNMPINDEX}],#1)<>last(/Ubiquiti
      AirOS by SNMP/net.if.status[ifOperStatus.{#SNMPINDEX}],#2))
    severity: average
    recovery_expression: last(/Ubiquiti AirOS by SNMP/net.if.status[ifOperStatus.{#SNMPINDEX}])<>2
      or 1=0
    allow_manual_close: true
