"""zbx init — interactive first-time setup wizard."""

from __future__ import annotations

import os
from pathlib import Path

import typer
from rich.console import Console
from rich.panel import Panel
from rich.prompt import Confirm, Prompt

console = Console()
app = typer.Typer()


_ENV_TEMPLATE = """\
# zbxctl configuration — generated by 'zbx init'
# Keep this file out of Git (it's already in .gitignore).

ZBX_URL={url}
ZBX_USER={user}
ZBX_PASSWORD={password}
ZBX_VERIFY_SSL={verify_ssl}
ZBX_TIMEOUT=30
"""

_GITIGNORE_ADDITIONS = [".env", "*.plan.json", "__pycache__/", "*.pyc"]


def _write_env(path: Path, url: str, user: str, password: str, verify_ssl: bool) -> None:
    path.write_text(
        _ENV_TEMPLATE.format(
            url=url,
            user=user,
            password=password,
            verify_ssl=str(verify_ssl).lower(),
        )
    )


def _ensure_gitignore(cwd: Path) -> None:
    gi = cwd / ".gitignore"
    existing = gi.read_text() if gi.exists() else ""
    additions = [e for e in _GITIGNORE_ADDITIONS if e not in existing]
    if additions:
        with gi.open("a") as f:
            if existing and not existing.endswith("\n"):
                f.write("\n")
            f.write("# zbxctl\n")
            for entry in additions:
                f.write(f"{entry}\n")


def _test_connection(url: str, user: str, password: str, verify_ssl: bool) -> tuple[bool, str]:
    """Try to authenticate; return (success, version_or_error)."""
    try:
        import requests  # noqa: PLC0415
        # Get API version (no auth needed)
        r = requests.post(
            f"{url.rstrip('/')}/api_jsonrpc.php",
            json={"jsonrpc": "2.0", "method": "apiinfo.version", "params": [], "id": 1},
            timeout=8,
            verify=verify_ssl,
        )
        r.raise_for_status()
        version = r.json().get("result", "unknown")

        # Try to authenticate
        auth_payload = {
            "jsonrpc": "2.0",
            "method": "user.login",
            "params": {"username": user, "password": password},
            "id": 2,
        }
        r2 = requests.post(
            f"{url.rstrip('/')}/api_jsonrpc.php",
            json=auth_payload, timeout=8, verify=verify_ssl,
        )
        r2.raise_for_status()
        result = r2.json()
        if "error" in result:
            return False, result["error"].get("data", "Authentication failed")
        return True, version
    except Exception as exc:  # noqa: BLE001
        return False, str(exc)


@app.callback(invoke_without_command=True)
def init_cmd(
    env_file: Path = typer.Option(Path(".env"), "--env-file", "-e",
                                  help="Path to write the .env file."),
    non_interactive: bool = typer.Option(False, "--yes", "-y",
                                         help="Skip prompts, use env vars directly."),
) -> None:
    """Interactive setup wizard — creates .env and project structure.

    Run once in a new project directory to configure your Zabbix connection.
    zbxctl will:

    \b
      1. Ask for your Zabbix URL, username, and password
      2. Test the connection
      3. Write a .env file
      4. Create configs/ directory structure
      5. Add .env to .gitignore

    Example:
      mkdir my-zabbix-config && cd my-zabbix-config
      zbx init
    """
    console.print()
    console.print(Panel.fit(
        "[bold cyan]zbxctl setup wizard[/bold cyan]\n"
        "[dim]Configure your Zabbix connection and project structure[/dim]",
        border_style="cyan",
    ))
    console.print()

    cwd = Path.cwd()

    # ── Already initialised? ──────────────────────────────────────────────
    if env_file.exists() and not non_interactive:
        overwrite = Confirm.ask(
            f"[yellow]{env_file} already exists.[/yellow] Overwrite?", default=False
        )
        if not overwrite:
            console.print("[dim]Keeping existing .env — nothing changed.[/dim]")
            raise typer.Exit(0)

    # ── Collect credentials ───────────────────────────────────────────────
    if non_interactive:
        url      = os.environ.get("ZBX_URL", "")
        user     = os.environ.get("ZBX_USER", "Admin")
        password = os.environ.get("ZBX_PASSWORD", "")
        if not url or not password:
            console.print("[red]✗[/red]  --yes requires ZBX_URL and ZBX_PASSWORD env vars.")
            raise typer.Exit(1)
        verify_ssl = os.environ.get("ZBX_VERIFY_SSL", "true").lower() != "false"
    else:
        url = Prompt.ask(
            "  Zabbix URL",
            default=os.environ.get("ZBX_URL", "http://localhost/zabbix"),
        ).rstrip("/")
        user = Prompt.ask(
            "  Username",
            default=os.environ.get("ZBX_USER", "Admin"),
        )
        password = Prompt.ask(
            "  Password",
            password=True,
            default=os.environ.get("ZBX_PASSWORD", ""),
        )
        verify_ssl = Confirm.ask("  Verify SSL certificate?", default=True)

    # ── Test connection ───────────────────────────────────────────────────
    console.print()
    with console.status("  Testing connection…"):
        ok, info = _test_connection(url, user, password, verify_ssl)

    if ok:
        console.print(f"  [green]✓[/green]  Connected to Zabbix {info}")
    else:
        console.print(f"  [yellow]⚠[/yellow]  Could not connect: {info}")
        if not non_interactive:
            proceed = Confirm.ask("  Save .env anyway?", default=False)
            if not proceed:
                console.print("[dim]Aborted.[/dim]")
                raise typer.Exit(1)

    # ── Write .env ────────────────────────────────────────────────────────
    _write_env(env_file, url, user, password, verify_ssl)
    console.print(f"  [green]✓[/green]  Wrote {env_file}")

    # ── Create project structure ──────────────────────────────────────────
    dirs = [
        cwd / "configs" / "templates",
        cwd / "configs" / "checks",
    ]
    for d in dirs:
        if not d.exists():
            d.mkdir(parents=True)
            console.print(f"  [green]✓[/green]  Created {d.relative_to(cwd)}/")

    # ── Update .gitignore ─────────────────────────────────────────────────
    _ensure_gitignore(cwd)
    console.print(f"  [green]✓[/green]  Updated .gitignore")

    # ── Next steps ────────────────────────────────────────────────────────
    console.print()
    console.print(Panel(
        f"[bold]You're ready![/bold]\n\n"
        f"  [cyan]zbx check list[/cyan]                   # browse 14 bundled checks\n"
        f"  [cyan]zbx check install postgresql[/cyan]     # copy + deploy a check\n"
        f"  [cyan]zbx plan configs/[/cyan]                # preview changes\n"
        f"  [cyan]zbx apply configs/[/cyan]               # apply to Zabbix\n"
        f"  [cyan]zbx export --all[/cyan]                 # migrate existing templates",
        title="Next steps",
        border_style="green",
    ))
    console.print()
